name: Download the release to a branch and push the branch

inputs:
  branch:
    description: "the branch to download files into"
    required: true
  repository:
    description: "The source repository path. Expected format {owner}/{repo}"
    required: true
  tag:
    description: "The github tag to download the release from"
    required: true
  patterns:
    description: "Download only assets that match a glob patterns"
    required: true
  dir:
    description: "The directory to download files into"
    required: true

runs:
  using: "composite"
  steps:
    - name: Switch to the branch
      run: git switch --orphan "${{ inputs.branch }}"
      shell: bash

    - name: Download the release
      run: |
        patterns=(${{ inputs.patterns }})
        gh release download --dir "${{ inputs.dir }}" --repo "${{ inputs.repository }}" "${{ inputs.tag }}" ${patterns[@]/#/-p }
        ls -l "${{ inputs.dir }}"
      shell: bash

    - name: Commit and Push
      if: success()
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "# ${{ inputs.branch }}" > README.md
          git add README.md
          git add "${{ inputs.dir }}"
          git commit -m "Generated by the action named download-to-branch"
          git push origin "${{ inputs.branch }}"
          git switch main
      shell: bash

    - name: Clean
      if: failure()
      run: |
        git rm -rf .
        git switch main
      shell: bash
