name: 'Mirror the release'
description: This action download the release of any public repository, commit it to a branch, and push the branch to your repository.

inputs:
  repository:
    description: The source repository path. Expected format {owner}/{repo}
    required: true
  tag:
    description: The github tag to download the release from
    required: true
  patterns:
    description: Download only assets that match a glob patterns
    required: true

runs:
  using: composite
  steps:
    - name: Checkout the branch of the release
      id: check_release
      run: |
        branch="${{ inputs.repository }}@${{ inputs.tag }}"
        if [[ -z "$(git ls-remote origin refs/heads/$branch)" ]]; then
          downloaded=no
        else
          downloaded=yes
        fi
        echo "::set-output name=downloaded::$downloaded"
      shell: bash

    - name: Download the release, commit and push it to the branch
      if: ${{ steps.check_release.outputs.downloaded == 'no' }}
      run: |
        declare -r branch="${{ inputs.repository }}@${{ inputs.tag }}"
        declare -r dir="${{ inputs.repository }}/${{ inputs.tag }}"
        declare -ar patterns=(${{ inputs.patterns }})
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        echo ${{ github.token }} | gh auth login --with-token
        git switch --orphan "$branch"
        gh release download --dir "$dir" --repo "${{ inputs.repository }}" "${{ inputs.tag }}" ${patterns[@]/#/-p}
        tar czvf - --directory="${{ inputs.repository }}" "${{ inputs.tag }}" | split -b 90M -d -a2 - "$dir.tar.gz."
        echo "# $branch" > README.md
        git add README.md
        git add "$dir.*"
        git commit -m "Generated by the action named download-to-branch"
        git push origin "$branch"
      shell: bash

    - name: Switch to the branch named main
      if: always()
      run: git switch --discard-changes main
      shell: bash
