name: Mirror the release of another repository to your repository
description: This action download the release of any public repository, commit it to a branch, and push the branch to your repository.
author: Wanli
branding:
  icon: upload-cloud
  color: green

inputs:
  repository:
    description: The source repository path. Expected format {owner}/{repo}
    required: true
  tag:
    description: The github tag to download the release from
    required: true
  patterns:
    description: Download only assets that match a glob patterns
    required: true

runs:
  using: composite
  steps:
    - name: Download the release, commit and push it to the branch
      run: |
        declare -r branch="${{ inputs.repository }}"
        declare -r dir="${{ inputs.tag }}"
        declare -ar patterns=(${{ inputs.patterns }})
        if [[ -n "$(git ls-remote origin refs/heads/$branch)" ]]; then
          echo "A branch name '$branch' already exists."
          exit 0
        fi

        git switch --orphan "$branch"
        
        echo "# ${{ inputs.repository }}@${{ inputs.tag }}" > README.md
        git add README.md

        echo ${{ github.token }} | gh auth login --with-token
        gh release download --dir "$dir" --repo "${{ inputs.repository }}" "${{ inputs.tag }}" ${patterns[@]/#/-p}
        tar Cczvf "$dir/.." - "${{ inputs.tag }}" | split -b 90M -d -a2 - "$dir.tar.gz."
        git add "$dir.tar.gz.*"

        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Generated by the action named 'download-to-branch'"
        git push origin "$branch"
      shell: bash

    - name: Switch to the branch named main
      if: always()
      run: git switch --discard-changes main
      shell: bash
