name: Test to mirror releases
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BRANCH: containerd/nerdctl
      DIRECTORY: v0.20.0
      REPOSITORY: containerd/nerdctl
      TAG: v0.20.0
      PATTERNS: nerdctl-0.20.0-linux-amd64.tar.gz SHA256SUMS* nerdctl-0.20.0-linux-arm*.tar.gz
      FILE_COUNT: 5
    steps:
    - uses: actions/checkout@v3

    - name: Delete the branch named ${{ env.BRANCH }} 
      run: |
        if [[ "$(git ls-remote origin refs/heads/${{ env.BRANCH }})" ]]; then
          git push --delete origin ${{ env.BRANCH }}
        fi
      shell: bash

    - name: Mirror the release of nerdctl
      uses: ./
      with:
        repository: ${{ env.REPOSITORY }}
        tag: ${{ env.TAG }}
        patterns: ${{ env.PATTERNS }}
    - name: Verify that all files downloaded
      run: __test__/verify-downloaded-files.sh "${{ env.BRANCH }}" "${{ env.DIRECTORY }}" "${{ env.PATTERNS }}" "${{ env.FILE_COUNT }}"
      shell: bash

    - name: Do not mirror the release if mirrored
      uses: ./
      with:
        repository: ${{ env.REPOSITORY }}
        tag: ${{ env.TAG }}
        patterns: SHA256SUMS*
    - name: Verify that all downloaded files is still there
      run: __test__/verify-downloaded-files.sh "${{ env.BRANCH }}" "${{ env.DIRECTORY }}" "${{ env.PATTERNS }}" "${{ env.FILE_COUNT }}"
      shell: bash

    - name: Delete the branch named ${{ env.BRANCH }}
      run: |
        if [[ "$(git ls-remote origin refs/heads/${{ env.BRANCH }})" ]]; then
          git push --delete origin ${{ env.BRANCH }}
        fi
      shell: bash
